name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-rate-limit-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-rate-limit
          path: |
            ~/.gitlibs
            ~/.m2

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - run: nix-build

      - run: nix-shell --run "clojure -M:test -e :redis"
